services:
  app:
    build: ./backend
    container_name: shopify
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/shopify
      - JWT_SECRET=your_jwt_secret_here
      - NODE_ENV=development 
      - PORT=5003
    ports:
      - "5003:5003"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: postgres-db2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopify
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: